### ISSUE TITLE
要素ごとの隙間が不一致

### ISSUE THREAD

**Issue by c0a2108119** [c0a21029/ProjExD#10]
https://github.com/c0a21029/ProjExD/blob/767cd62cdd0050eb7224bbf77c897e494352a776/ex03/maze.py#L51
場所によって()内の要素を分ける「,」の後に空白を入れている箇所と、入れていない箇所があります。どちらかに統一してはどうでしょうか。すべて、一つ分の空白があるように変更する方が個人的には好みです。

**Comment by c0a21029** [comment]
修正しました
