### ISSUE TITLE
返す値がないのなら、returnはいらないのではないでしょうか? 101行目も

### ISSUE THREAD

**Issue by kotaokuda** [c0a21029/ProjExD#13]
https://github.com/c0a21029/ProjExD/blob/47237d4c78bad72e5a24705be205d0a03f125807/ex04/dodge_bomb.py#L19

**Comment by c0a21029** [comment]
これらの場所にreturnをいれないと、やり直した回数分×を押さないと消せなくなってしまうため消せませんでした。恐らく裏でwhileが継続されてしまうのが原因だと思いますが、解決方法が分かりませんでした。
