### ISSUE TITLE
これと言って突っ込みたい点が見つかりませんでした

### ISSUE THREAD

**Issue by c0a2108119** [c0a21029/ProjExD#15]
https://github.com/c0a21029/ProjExD/blob/4e22ae18a1646613504a1f5b37107438996b2ce2/ex04/dodge_bomb.py#L20
強いてあげるなら、def retry()とdef main()の間に一行隙間を開けるとかどうでしょうか。少し見やすくなるかもしれない。(今でも、十分見やすい気もしますが)

**Comment by c0a21029** [comment]
ご指摘の点を調整しました
