### ISSUE TITLE
35行目でも変数としてCを利用していますが、必要ですか？別の変数なら、別の文字に変えた方が良い気がする

### ISSUE THREAD

**Issue by c0a2108119** [c0a21029/ProjExD#5]
https://github.com/c0a21029/ProjExD/blob/66b7250e2d35b5c63a46f71cb09db5f3787b9063/ex02/calc.py#L57

**Comment by c0a21029** [comment]
座標の変数についてはコードに一貫性を持たせるために統一したいと考えています。
