### ISSUE TITLE
謎のWowボタン

### ISSUE THREAD

**Issue by nisiyama158** [c0a21029/ProjExD#6]
https://github.com/c0a21029/ProjExD/blob/66b7250e2d35b5c63a46f71cb09db5f3787b9063/ex02/calc.py#L66

遊び心のあるボタンで良いなと感じました。ただ、電卓機能の近くにあるので、出来ればもう少し遠ざけると誤作動しなくて良いと思います（正直さじ加減によると思うので、無視して貰ってもかまわないです）。

＃記号の部分に関して、for文を一つにまとめられる気もしました。

**Comment by c0a21029** [comment]
Wowの文字色を青くし、背景色との補色効果によって視認性をあげ誤作動を抑制しました。
