### ISSUE TITLE
これは意味があるのでしょうか?　次でjid定義されてしまいますが

### ISSUE THREAD

**Issue by kotaokuda** [c0a21029/ProjExD#9]
https://github.com/c0a21029/ProjExD/blob/767cd62cdd0050eb7224bbf77c897e494352a776/ex03/maze.py#L36

**Comment by c0a21029** [comment]
jidが初回では設定されてない状態ですが、ゴールに到着するときにはjidが設定されていると判断してここに配置しました。
また、このコードを抜くと終了処理がされず永遠にゴールのポップアウトが出てくるようになるため抜けませんでした。
